### PR TITLE
Fixes for resource reference resolution templates

### PR DESCRIPTION
**Pull request by jljaco**
Fix for code originally in:  https://github.com/aws-controllers-k8s/code-generator/pull/401

Description of changes:
There were some syntax errors in generated controller code for resource reference resolution.  See [here](https://prow.ack.aws.dev/view/s3/ack-prow-logs/logs/auto-generate-controllers/1623784341903511552) for some examples of compilation errors

Fixes here:
- correct use of double-quotes in error messages

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
Yeah this was a good lesson about using `%q` in generated code. Thanks

**Comment by jljaco** [comment]
We decided to revert #401 and #412 instead of fixing issues; closing this one but the fix here should be incorporated into the future un-revert PR
